# Generated by Django 3.1.7 on 2021-05-20 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_membership_active'),
        ('people', '0003_auto_20210427_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_used_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company'),
        ),
    ]
