version: '3.7'

services:
  db:
    image: "postgres:11"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:4300
    volumes:
      - .:/code
    ports:
      - 4300:4300
    depends_on:
      - db

volumes:
  postgres_data: