# Generated by Django 3.1.7 on 2021-06-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20210610_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalentity',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='externalentity',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
