# Generated by Django 3.1.7 on 2021-04-21 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=120, null=True)),
                ('comment', models.TextField(null=True)),
                ('paid', models.BooleanField(default=False)),
                ('debt_expiration_date', models.DateTimeField(null=True)),
                ('installments_number', models.SmallIntegerField(default=1)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.service')),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.externalentity')),
            ],
            bases=('transactions.transaction',),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transactions.transaction')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.externalentity')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            bases=('transactions.transaction',),
        ),
    ]
