# Generated by Django 3.1.7 on 2021-04-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='externalentity',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
